
CREATE TABLE IF NOT EXISTS STUDENT
(
	_ID					INTEGER			PRIMARY KEY		AUTOINCREMENT,
	NAME				VARCHAR(100)	    NOT NULL,
	CLUB_BRANCH			VARCHAR(100)		NOT NULL,
	CURRENT_RANK		VARCHAR(100)		NOT NULL,
	HOME_PHONE			VARCHAR(100)	    NOT NULL,
	GRADING_LOCATION	VARCHAR(100)		NOT NULL,
	DATE_OF_GRADING     VARCHAR(100)		NOT NULL,
	GENDER              VARCHAR(100)		NOT NULL,
	DATE_OF_BIRTH       VARCHAR(100)		NOT NULL,
	AGE                 VARCHAR(100)		NOT NULL,
	CURRENT_WEIGHT      VARCHAR(100)		NOT NULL,
	HEIGHT              VARCHAR(100)		NOT NULL,
	MOBILE              VARCHAR(100)		NOT NULL,
	GRADING_FEE         VARCHAR(100)		NOT NULL,
	STARTING_TIME       VARCHAR(100)        NOT NULL
);


CREATE TABLE IF NOT EXISTS ASSESMENT
(
   _ID					INTEGER			PRIMARY KEY		AUTOINCREMENT,
   MANNER               VARCHAR(100)        DEFAULT NULL,
   STANCES              VARCHAR(100)		DEFAULT NULL,
   SHORT_STANCES        VARCHAR(100)		DEFAULT NULL,
   STRIKES              VARCHAR(100)		DEFAULT NULL,
   STRIKES_TRIPLE       VARCHAR(100)		DEFAULT NULL,
   BOXING_SKILL         VARCHAR(100)		DEFAULT NULL,
   BLOCKS               VARCHAR(100)		DEFAULT NULL,
   BLOCKS_DOUBLE        VARCHAR(100)		DEFAULT NULL,
   KICK                 VARCHAR(100)		DEFAULT NULL,
   FRONT_KICK           VARCHAR(100)		DEFAULT NULL,
   SLIDE_KICK           VARCHAR(100)		DEFAULT NULL,
   ROUNDHOUSE_KICK      VARCHAR(100)		DEFAULT NULL,
   BASIC_FORM           VARCHAR(100)		DEFAULT NULL,
   TAEGUK_BY_COUNT      VARCHAR(100)		DEFAULT NULL,
   TAEGUK__FREE         VARCHAR(100)		DEFAULT NULL,
   ONE_STEP_SPARRING    VARCHAR(100)		DEFAULT NULL,
   SPARRING             VARCHAR(100)		DEFAULT NULL,
   YELL                 VARCHAR(100)		DEFAULT NULL,
   FEEDBACK_POSITIVE    VARCHAR(100)		DEFAULT NULL,
   FEEDBACK_NEGETIVE    VARCHAR(100)		DEFAULT NULL,
   RECOMMENDED_BY       VARCHAR(100)		DEFAULT NULL,
   RECOMMENDED_DATE     VARCHAR(100)		DEFAULT NULL,
   GRADING_EXAMINER     VARCHAR(100)		DEFAULT NULL,
   GRADING_DATE         VARCHAR(100)		DEFAULT NULL,
   PERCENTAGE           VARCHAR(100)		DEFAULT NULL,
   STUDENT_ID           VARCHAR(100)		DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS RESULT
(
   _ID					INTEGER			PRIMARY KEY		AUTOINCREMENT,
   STUDENT_ID           VARCHAR(100)		NOT NULL,
   GRADE                VARCHAR(100)		NOT NULL
);


--CREATE TABLE IF NOT EXISTS LAND_INFORMATION(
--    LAND_IDENTIFIER             VARCHAR(36) NOT NULL,
--    LAND_NAME                   VARCHAR(36) NOT NULL,
--	LAND_TYPE_IDENTIFIER        VARCHAR(36) NOT NULL,
--	FARMER_IDENTIFIER           VARCHAR(36) NOT NULL,
--	LAND_DESCRIPTION            VARCHAR(1000) NULL,
--    LAND_LOCATION               VARCHAR(36) NOT NULL,
--	LAND_SIZE                   VARCHAR(50) NOT NULL,
--    UNIT                        VARCHAR(50) ,
--    CONVERSION_RATE             VARCHAR(50),
--	LAST_UPDATED VARCHAR(36)  DEFAULT NULL,
--	IS_DELETED BOOLEAN          DEFAULT NULL,
--    PRIMARY KEY(LAND_IDENTIFIER),
--    CONSTRAINT LIFK FOREIGN KEY(FARMER_IDENTIFIER) REFERENCES FARMER_INFORMATION(FARMER_IDENTIFIER)
--);


--  INSERT OR IGNORE INTO MODULE_INFO VALUES ('c1b2b9f4-8018-11e2-848f-cc52af8af9fc', 'module2', 'mrittika', 'module to handle fertilizer', NULL, '0');
--  INSERT OR IGNORE INTO MODULE_INFO VALUES ('fe7281f8-3833-4a99-bfe5-a52cda5a5d8a', 'module1', 'ankur', 'module to handle seed', NULL, '0');
--  INSERT OR IGNORE INTO MODULE_INFO VALUES ('931196bc-a289-11e2-a0bf-cc52af8af9fc', 'module3', 'protikar', 'module to handle pestiside', NULL, '0');
--  INSERT OR IGNORE INTO MODULE_INFO VALUES ('0e42f1b1-c76e-4b22-9823-651e2e158023', 'module4', 'vistar', 'module to handle buyers', NULL, '0');

/***********End: DML******************/